### ISSUE TITLE
💔 [Malformed]: uBlock Origin does not ingest the Anti-Anti-Adblock Scriptlet

### ISSUE THREAD

**Issue by Metrokoto** [the-advoid/ad-void#3063]
The issue is with [AdVoid.Scriptlets.AntiAntiAdBlock.txt](https://github.com/the-advoid/ad-void/blob/main/scriptlets/AdVoid.Scriptlets.AntiAntiAdBlock.txt).

This list does not appear to be compatible with uBlock Origin for some reason, as it shows:
``AdVoid.Scriptlets.AntiAntiAdBlock 0 used out of 0``
when checking in the list viewer.

Perhaps it is to do with the rule format?

**Comment by igorskyflyer** [comment]
I have used the given scriptlets on my Android phone in the AdGuard application and they worked fine, I will investigate the issue further, it might be a compatibility issue.

**Comment by igorskyflyer** [comment]
Fixed with [c0646ce](https://github.com/the-advoid/ad-void/commit/c0646ce5b262ab1d9293474bafd84d5370dab91d).
